// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:koaa/app/data/models/budget.dart';
import 'package:koaa/app/data/models/category.dart';
import 'package:koaa/app/data/models/debt.dart';
import 'package:koaa/app/data/models/financial_goal.dart';
import 'package:koaa/app/data/models/job.dart';
import 'package:koaa/app/data/models/local_transaction.dart';
import 'package:koaa/app/data/models/local_user.dart';
import 'package:koaa/app/data/models/ml/financial_pattern.dart';
import 'package:koaa/app/data/models/ml/ml_model_state.dart';
import 'package:koaa/app/data/models/ml/user_financial_profile.dart';
import 'package:koaa/app/data/models/recurring_transaction.dart';
import 'package:koaa/app/data/models/savings_goal.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(DebtAdapter());
    registerAdapter(DebtTypeAdapter());
    registerAdapter(FinancialGoalAdapter());
    registerAdapter(FinancialPatternAdapter());
    registerAdapter(FrequencyAdapter());
    registerAdapter(GoalMilestoneAdapter());
    registerAdapter(JobAdapter());
    registerAdapter(LocalTransactionAdapter());
    registerAdapter(LocalUserAdapter());
    registerAdapter(MLModelStateAdapter());
    registerAdapter(PaymentFrequencyAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(SavingsGoalAdapter());
    registerAdapter(TransactionCategoryAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserFinancialProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(DebtAdapter());
    registerAdapter(DebtTypeAdapter());
    registerAdapter(FinancialGoalAdapter());
    registerAdapter(FinancialPatternAdapter());
    registerAdapter(FrequencyAdapter());
    registerAdapter(GoalMilestoneAdapter());
    registerAdapter(JobAdapter());
    registerAdapter(LocalTransactionAdapter());
    registerAdapter(LocalUserAdapter());
    registerAdapter(MLModelStateAdapter());
    registerAdapter(PaymentFrequencyAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(SavingsGoalAdapter());
    registerAdapter(TransactionCategoryAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserFinancialProfileAdapter());
  }
}
