// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:koaa/app/data/models/local_transaction.dart';
import 'package:koaa/app/data/models/local_user.dart';
import 'package:koaa/app/data/models/recurring_transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FrequencyAdapter());
    registerAdapter(LocalTransactionAdapter());
    registerAdapter(LocalUserAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(TransactionCategoryAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FrequencyAdapter());
    registerAdapter(LocalTransactionAdapter());
    registerAdapter(LocalUserAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(TransactionCategoryAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}
